source 'https://github.com/CocoaPods/Specs.git'

#platform :ios, '6.0'

target 'RPLPhotoLibraryView', :exclusive => true do
  pod "RPLPhotoLibraryView", :path => "../"

  pod 'ResplendentUtilities', '0.1.1'
end

target 'Tests', :exclusive => true do
  pod "RPLPhotoLibraryView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
